<?php
declare(strict_types=1);
namespace App\Controller;
use App\Core\{Database,Request,Response,Validator};
use App\Service\ParentService;
final class ChatController{
 public function contacts(Request $r,array $p):never{$student=Validator::id($r->query('studentId'),'studentId');$c=ParentService::student($p,$student);$sql="SELECT DISTINCT CONVERT(varchar(64),t.ApiUserID) teacherId,t.DisplayName name,t.EmployeeID employeeId,'subject_teacher' role FROM ApiTeacherAssignment a JOIN SchoolTeacher t ON t.ApiUserID=a.ApiUserID WHERE a.OwnerSessionID=? AND a.ClassID=? AND a.SectionID=? AND a.IsActive=1 AND t.IsActive=1 UNION SELECT DISTINCT CONVERT(varchar(64),t.ApiUserID),t.DisplayName,t.EmployeeID,m.TeacherRole FROM AppClassTeacher m JOIN SchoolTeacher t ON CONVERT(varchar(64),t.ApiUserID)=CONVERT(varchar(64),m.ApiUserID) WHERE m.OwnerSessionID=? AND m.ClassID=? AND m.SectionID=? AND m.IsActive=1 AND t.IsActive=1";$st=Database::connection()->prepare($sql);$st->execute([$c['OwnerSessionID'],$c['ClassID'],$c['SectionID'],$c['OwnerSessionID'],$c['ClassID'],$c['SectionID']]);Response::success(['contacts'=>$st->fetchAll()]);}
 public function history(Request $r,array $p,string $conversation):never{$conversation=Validator::id($conversation,'conversationId');$db=Database::connection();$st=$db->prepare('SELECT TOP 1 AppChatConversationID FROM AppChatConversation WHERE AppChatConversationID=? AND AppParentID=?');$st->execute([$conversation,$p['AppParentID']]);if(!$st->fetchColumn())Response::error('Conversation not found.',404,'CHAT_NOT_FOUND');$q=$db->prepare('SELECT m.AppChatMessageID id,m.SenderType senderType,m.SenderID senderId,m.Message message,m.SentAt sentAt,m.ReadAt readAt,a.AppChatAttachmentID attachmentId,a.FileName fileName,a.MimeType mimeType,a.FileUrl fileUrl,a.FileSize fileSize FROM AppChatMessage m LEFT JOIN AppChatAttachment a ON a.AppChatMessageID=m.AppChatMessageID WHERE m.AppChatConversationID=? ORDER BY m.SentAt,m.AppChatMessageID');$q->execute([$conversation]);Response::success(['conversationId'=>$conversation,'messages'=>$q->fetchAll()]);}
 public function send(Request $r,array $p):never{$d=$r->json();Validator::required($d,['studentId','teacherId','message']);$student=Validator::id($d['studentId'],'studentId');ParentService::student($p,$student);$teacher=(string)$d['teacherId'];$db=Database::connection();$id=self::conversation($db,(int)$p['AppParentID'],$student,$teacher);$st=$db->prepare("INSERT INTO AppChatMessage(AppChatConversationID,SenderType,SenderID,Message) OUTPUT INSERTED.AppChatMessageID VALUES(?,'parent',?,?)");$st->execute([$id,$p['AppParentID'],trim((string)$d['message'])]);$message=(int)$st->fetchColumn();$db->prepare('UPDATE AppChatConversation SET UpdatedAt=SYSUTCDATETIME() WHERE AppChatConversationID=?')->execute([$id]);Response::success(['conversationId'=>$id,'messageId'=>$message,'sent'=>true],201);}
 public function attachment(Request $r,array $p):never{$d=$r->json();Validator::required($d,['studentId','teacherId','fileName','mimeType','fileUrl']);$student=Validator::id($d['studentId'],'studentId');ParentService::student($p,$student);$db=Database::connection();$id=self::conversation($db,(int)$p['AppParentID'],$student,(string)$d['teacherId']);$m=$db->prepare("INSERT INTO AppChatMessage(AppChatConversationID,SenderType,SenderID,Message) OUTPUT INSERTED.AppChatMessageID VALUES(?,'parent',?,?)");$m->execute([$id,$p['AppParentID'],$d['message']??null]);$mid=(int)$m->fetchColumn();$a=$db->prepare('INSERT INTO AppChatAttachment(AppChatMessageID,FileName,MimeType,FileUrl,FileSize) OUTPUT INSERTED.AppChatAttachmentID VALUES(?,?,?,?,?)');$a->execute([$mid,substr((string)$d['fileName'],0,255),substr((string)$d['mimeType'],0,150),substr((string)$d['fileUrl'],0,1000),isset($d['fileSize'])?(int)$d['fileSize']:null]);Response::success(['conversationId'=>$id,'messageId'=>$mid,'attachmentId'=>(int)$a->fetchColumn()],201);}
 public function read(Request $r,array $p,string $conversation):never{$conversation=Validator::id($conversation,'conversationId');$st=Database::connection()->prepare("UPDATE m SET ReadAt=SYSUTCDATETIME() FROM AppChatMessage m JOIN AppChatConversation c ON c.AppChatConversationID=m.AppChatConversationID WHERE c.AppChatConversationID=? AND c.AppParentID=? AND m.SenderType='teacher' AND m.ReadAt IS NULL");$st->execute([$conversation,$p['AppParentID']]);Response::success(['updated'=>$st->rowCount()]);}
 private static function conversation(\PDO $db,int $parent,int $student,string $teacher):int{$st=$db->prepare('SELECT TOP 1 AppChatConversationID FROM AppChatConversation WHERE AppParentID=? AND StudentID=? AND TeacherApiUserID=?');$st->execute([$parent,$student,$teacher]);$id=$st->fetchColumn();if($id)return(int)$id;$insert=$db->prepare('INSERT INTO AppChatConversation(AppParentID,StudentID,TeacherApiUserID) OUTPUT INSERTED.AppChatConversationID VALUES(?,?,?)');$insert->execute([$parent,$student,$teacher]);return(int)$insert->fetchColumn();}
}
