<?php
declare(strict_types=1);
namespace App\Controller;
use App\Core\{Database,Request,Response};
use App\Service\{LegacyMapper,ParentService,SimplePdf};

final class FeeController {
    public function summary(Request $r,array $p,int $student):never{
        ParentService::student($p,$student);$dues=$this->normalizedFees($student);$receipts=$this->normalizedReceipts($student);$summary=$this->summaryData($dues,$receipts);
        Response::success(array_merge(['studentId'=>$student],$summary));
    }
    public function list(Request $r,array $p,int $student):never{ParentService::student($p,$student);Response::success(['studentId'=>$student,'fees'=>$this->normalizedFees($student)]);}
    public function detail(Request $r,array $p,int $student,int $fee):never{
        ParentService::student($p,$student);$st=Database::connection()->prepare('SELECT TOP 1 * FROM StudentFees WHERE StudentID=? AND StudentFeesID=?');$st->execute([$student,$fee]);$row=$st->fetch();if(!$row)Response::error('Fee record not found.',404,'FEE_NOT_FOUND');
        $items=Database::connection()->prepare('SELECT * FROM StudentFeesItem WHERE StudentID=? AND StudentFeesID=? ORDER BY StudentFeesItemID');$items->execute([$student,$fee]);Response::success(['fee'=>$row,'items'=>$items->fetchAll()]);
    }
    public function account(Request $r,array $p,int $student):never{ParentService::student($p,$student);$dues=$this->normalizedFees($student);$receipts=$this->normalizedReceipts($student);$summary=$this->summaryData($dues,$receipts);$transactions=$this->ledger($dues,$receipts);Response::success(array_merge(['studentId'=>$student],$summary,['summary'=>$summary,'transactions'=>$transactions,'items'=>$transactions,'ledger'=>$transactions,'feeAccount'=>$transactions,'fee_account'=>$transactions,'statement'=>$transactions,'statements'=>$transactions,'records'=>$transactions,'list'=>$transactions,'entries'=>$transactions,'history'=>$transactions,'dues'=>$dues,'fees'=>$dues,'receipts'=>$receipts]));}
    public function accountDownload(Request $r,array $p,int $student):never{$studentRow=ParentService::student($p,$student);$dues=$this->normalizedFees($student);$receipts=$this->normalizedReceipts($student);SimplePdf::feeStatement($this->studentData($studentRow,$student),$this->summaryData($dues,$receipts),$dues,$receipts,"fee-account-{$student}.pdf");}
    public function payments(Request $r,array $p,int $student):never{ParentService::student($p,$student);$st=Database::connection()->prepare('SELECT AppPaymentID id,Amount amount,Currency currency,Provider provider,ProviderOrderID providerOrderId,ProviderPaymentID providerPaymentId,Status status,CreatedAt createdAt,UpdatedAt updatedAt FROM AppPayment WHERE AppParentID=? AND StudentID=? ORDER BY CreatedAt DESC');$st->execute([$p['AppParentID'],$student]);Response::success(['payments'=>$st->fetchAll()]);}
    public function receipts(Request $r,array $p,int $student):never{ParentService::student($p,$student);$receipts=$this->normalizedReceipts($student);Response::success(['studentId'=>$student,'receipts'=>$receipts,'items'=>$receipts]);}
    public function receipt(Request $r,array $p,int $receipt):never{
        $db=Database::connection();$st=$db->prepare("SELECT TOP 1 'app' source,ar.AppReceiptID id,ar.StudentID studentId,ar.ReceiptNumber receiptNumber,CAST(ar.Amount AS float) amount,ar.ReceiptDate receiptDate,ar.PaymentMode paymentMode,ar.PdfPath pdfPath FROM AppReceipt ar JOIN AppParentStudent l ON l.StudentID=ar.StudentID WHERE ar.AppReceiptID=? AND l.AppParentID=?");$st->execute([$receipt,$p['AppParentID']]);$row=$st->fetch();
        if(!$row){$st=$db->prepare("SELECT TOP 1 'legacy' source,fr.* FROM FeeReceipt fr JOIN AppParentStudent l ON l.StudentID=fr.StudentID WHERE fr.FeeReceiptID=? AND l.AppParentID=?");$st->execute([$receipt,$p['AppParentID']]);$row=$st->fetch();}
        if(!$row)Response::error('Receipt not found.',404,'RECEIPT_NOT_FOUND');Response::success(['receipt'=>$this->normalizeReceipt($row)]);
    }
    public function download(Request $r,array $p,int $receipt):never{
        $st=Database::connection()->prepare('SELECT TOP 1 ar.ReceiptNumber,ar.PdfPath FROM AppReceipt ar JOIN AppParentStudent l ON l.StudentID=ar.StudentID WHERE ar.AppReceiptID=? AND l.AppParentID=?');$st->execute([$receipt,$p['AppParentID']]);$row=$st->fetch();
        $base=realpath(dirname(__DIR__,2).'/storage/receipts');$file=$row&&$base?realpath($base.DIRECTORY_SEPARATOR.ltrim((string)$row['PdfPath'],'/\\')):false;
        if(!$file||!str_starts_with($file,$base.DIRECTORY_SEPARATOR)||!is_file($file)){$receipt=$this->receiptRow($p,$receipt);if(!$receipt)Response::error('Receipt not found.',404,'RECEIPT_NOT_FOUND');$normalized=$this->normalizeReceipt($receipt);$studentRow=ParentService::student($p,(int)$normalized['studentId']);SimplePdf::feeReceipt($normalized,$this->studentData($studentRow,(int)$normalized['studentId']),'receipt-'.$normalized['id'].'.pdf');}
        header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9_-]/','',(string)$row['ReceiptNumber']).'.pdf"');header('Content-Length: '.filesize($file));readfile($file);exit;
    }
    private function feesFor(int $student):array{try{$st=Database::connection()->prepare('SELECT * FROM StudentFees WHERE StudentID=? ORDER BY StudentFeesID DESC');$st->execute([$student]);return$st->fetchAll();}catch(\PDOException){return[];}}
    private function receiptsFor(int $student):array{$all=[];try{$legacy=Database::connection()->prepare("SELECT 'legacy' source,* FROM FeeReceipt WHERE StudentID=? ORDER BY FeeReceiptID DESC");$legacy->execute([$student]);$all=$legacy->fetchAll();}catch(\PDOException){}try{$app=Database::connection()->prepare("SELECT 'app' source,AppReceiptID id,AppPaymentID,StudentID,ReceiptNumber,Amount,ReceiptDate,PaymentMode,PdfPath FROM AppReceipt WHERE StudentID=? ORDER BY ReceiptDate DESC");$app->execute([$student]);$all=array_merge($app->fetchAll(),$all);}catch(\PDOException){}return$all;}
    private function receiptRow(array $p,int $receipt):array|false{$db=Database::connection();try{$st=$db->prepare("SELECT TOP 1 'app' source,ar.AppReceiptID id,ar.StudentID studentId,ar.ReceiptNumber receiptNumber,ar.Amount amount,ar.ReceiptDate receiptDate,ar.PaymentMode paymentMode FROM AppReceipt ar JOIN AppParentStudent l ON l.StudentID=ar.StudentID WHERE ar.AppReceiptID=? AND l.AppParentID=?");$st->execute([$receipt,$p['AppParentID']]);if($x=$st->fetch())return$x;}catch(\PDOException){}try{$st=$db->prepare("SELECT TOP 1 'legacy' source,fr.FeeReceiptID id,fr.* FROM FeeReceipt fr JOIN AppParentStudent l ON l.StudentID=fr.StudentID WHERE fr.FeeReceiptID=? AND l.AppParentID=?");$st->execute([$receipt,$p['AppParentID']]);return$st->fetch();}catch(\PDOException){return false;}}
    private function normalizedFees(int $student):array{return array_map(fn($x)=>$this->normalizeFee($x),$this->feesFor($student));}
    private function normalizedReceipts(int $student):array{return array_map(fn($x)=>$this->normalizeReceipt($x),$this->receiptsFor($student));}
    private function normalizeFee(array $x):array{$id=(int)LegacyMapper::value($x,['StudentFeesID','id'],0);$date=LegacyMapper::date(LegacyMapper::value($x,['DueDate','FeeDate','Date','CreatedAt']));$description=(string)LegacyMapper::value($x,['FeeName','Title','Description','Particular'],'School fee');$amount=LegacyMapper::money(LegacyMapper::value($x,['NetFee','Amount','FeeAmount','TotalAmount']));$discount=LegacyMapper::money(LegacyMapper::value($x,['Discount','MDisc','DiscountAmount']));$paid=LegacyMapper::money(LegacyMapper::value($x,['PaidAmount','ReceiveAmount','ReceivedAmount'],0));$balance=round(max(0,$amount-$discount-$paid),2);return['id'=>$id,'feeId'=>$id,'date'=>$date,'dueDate'=>$date,'description'=>$description,'title'=>$description,'amount'=>$amount,'feeAmount'=>$amount,'totalAmount'=>$amount,'discount'=>$discount,'discountAmount'=>$discount,'paid'=>$paid,'paidAmount'=>$paid,'balance'=>$balance,'balanceAmount'=>$balance];}
    private function normalizeReceipt(array $x):array{$id=(int)LegacyMapper::value($x,['id','AppReceiptID','FeeReceiptID'],0);$studentId=(int)LegacyMapper::value($x,['studentId','StudentID'],0);$number=(string)LegacyMapper::value($x,['receiptNumber','ReceiptNumber','VoucherNo','VoucherStr'],(string)$id);$date=LegacyMapper::date(LegacyMapper::value($x,['receiptDate','ReceiptDate','Dated','Date']))??'';$amount=LegacyMapper::money(LegacyMapper::value($x,['amount','Amount','ReceiveAmount','PaidAmount','NetAmount']));$rawBalance=LegacyMapper::value($x,['Balance','BalanceAmount','DueAmount','RemainAmount','RemainingAmount']);$balance=LegacyMapper::money($rawBalance);$mode=(string)LegacyMapper::value($x,['paymentMode','PaymentMode','ModeName','PayMode'],'-');$download='/api/receipts/'.$id.'/download';return['id'=>$id,'receiptId'=>$id,'studentId'=>$studentId,'receiptNumber'=>$number,'receiptNo'=>$number,'voucherNumber'=>$number,'voucherNo'=>$number,'date'=>$date,'receiptDate'=>$date,'paymentDate'=>$date,'amount'=>$amount,'paidAmount'=>$amount,'balance'=>$balance,'balanceAmount'=>$balance,'balanceKnown'=>$rawBalance!==null&&is_numeric($rawBalance),'paymentMode'=>$mode,'mode'=>$mode,'status'=>'paid','description'=>'Receipt '.$number,'source'=>(string)LegacyMapper::value($x,['source'],'legacy'),'downloadUrl'=>$download,'downloadPath'=>$download];}
    private function summaryData(array $dues,array $receipts):array{$billed=array_sum(array_column($dues,'amount'));$discount=array_sum(array_column($dues,'discount'));$paid=array_sum(array_column($receipts,'amount'));$sorted=$receipts;usort($sorted,static fn($a,$b)=>strcmp((string)($b['date']??''),(string)($a['date']??'')));$knownBalance=null;foreach($sorted as $receipt)if($receipt['balanceKnown']??false){$knownBalance=(float)$receipt['balance'];break;}$balance=$knownBalance??max(0,$billed-$discount-$paid);$total=max($billed,$paid+$balance+$discount);return['totalDue'=>round($total,2),'totalFee'=>round($total,2),'totalAmount'=>round($total,2),'feeAmount'=>round($total,2),'netFee'=>round($total,2),'discount'=>round($discount,2),'discountAmount'=>round($discount,2),'paid'=>round($paid,2),'paidAmount'=>round($paid,2),'balance'=>round($balance,2),'balanceAmount'=>round($balance,2),'currency'=>'INR'];}
    private function ledger(array $dues,array $receipts):array{$rows=[];foreach($dues as $x)$rows[]=array_merge($x,['type'=>'due','transactionType'=>'due','title'=>(string)($x['description']??'School fee'),'description'=>(string)($x['description']??'School fee'),'date'=>(string)($x['date']??''),'dueDate'=>(string)($x['dueDate']??$x['date']??''),'amount'=>(float)($x['amount']??0),'due'=>(float)($x['amount']??0),'paid'=>(float)($x['paid']??0),'balance'=>(float)($x['balance']??0),'status'=>'due']);foreach($receipts as $x){$desc='Receipt '.($x['receiptNumber']??$x['id']??'');$rows[]=array_merge($x,['type'=>'receipt','transactionType'=>'payment','title'=>$desc,'description'=>$desc,'date'=>(string)($x['date']??''),'dueDate'=>(string)($x['date']??''),'amount'=>(float)($x['amount']??0),'due'=>0.0,'paid'=>(float)($x['amount']??0),'balance'=>(float)($x['balance']??0),'status'=>'paid']);}usort($rows,static fn($a,$b)=>strcmp((string)($b['date']??''),(string)($a['date']??'')));return$rows;}
    private function studentData(array $x,int $id):array{try{$st=Database::connection()->prepare('SELECT TOP 1 * FROM Student WHERE StudentID=?');$st->execute([$id]);$x=array_merge($x,$st->fetch()?:[]);}catch(\PDOException){}return['id'=>$id,'name'=>(string)LegacyMapper::value($x,['StudentName','Name','studentName','FirstName'],'Student'),'admissionNo'=>(string)LegacyMapper::value($x,['AdmissionNo','AdmissionNumber','admissionNo','ScholarNo'],'-')];}
}
